# Generated by Django 4.0.3 on 2022-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('psw', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='vehicledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si', models.IntegerField()),
                ('plate_num', models.CharField(max_length=20)),
                ('dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'vehicledb',
            },
        ),
    ]
