# Generated by Django 4.1.2 on 2022-12-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uname',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
